---
title: "Lecture2"
author: "CPG"
date: "9/7/2021"
output: html_document
---

```{r}
library(tidyverse)
library(scales)
library(plotly)
library(lemon)
library(lubridate)

moviesAreTheBest <- read.csv("../R/movie_profit-1.csv")
options(scipen = 999)
```

```{r}
View(moviesAreTheBest)
```


```{r}
# Count movies by MPAA Rating
moviesAreTheBest %>%
  ggplot(aes(x=mpaa_rating)) +
  geom_bar()
```

```{r}
moviesAreTheBest %>%
  group_by(mpaa_rating) %>%
  summarize(sum_budget = sum(production_budget)) %>%
  ggplot(aes(x=mpaa_rating,y=sum_budget)) +
  geom_col() 
```

```{r}
summarized_movies <- moviesAreTheBest %>%
  group_by(mpaa_rating) %>%
  summarize(sum_budget = sum(production_budget))

summarized_movies
```

```{r}
moviesAreTheBest %>%
  ggplot(aes(x=mpaa_rating,y=production_budget)) +
  geom_col() +
  facet_rep_wrap(~genre, repeat.tick.labels = TRUE) + # create graph for each genre // (repeat.tick.labels = TRUE) adds labels to all graphs
  scale_y_continuous(labels = dollar_format()) + #add $ to y axis labels
  labs(title="Production Budget by MPAA Rating", x = "MPAA Rating", y = "Production Budget")
```


```{r}
#3 
ggplot(data = moviesAreTheBest) + 
  aes(x = mpaa_rating, y = worldwide_gross) + 
  scale_y_continuous(labels = dollar_format()) + # missing parens 
  geom_col() + #geom_col not geom_bar
  labs(title = "Worldwide Gross Revenue by MPAA Rating", x = "MPAA Rating", y = "Worldwide Gross Revenue") + 
  facet_rep_wrap(~genre, repeat.tick.labels = TRUE) #facet_rep_wrap not facet_wrap
```


```{r}
# Filtering with the Pipe Operator 
moviesAreTheBest %>%
  filter(distributor == "Walt Disney") %>%
  ggplot(aes(x=genre)) +
  geom_bar()
  
```

```{r}
moviesAreTheBest %>%
  filter(distributor == "Walt Disney") %>%
  ggplot(aes(x=production_budget)) +
  scale_x_continuous(labels = dollar_format()) +
  geom_histogram()
```

```{r}
filter_distributor <- c("Walt Disney", "Universal")
```

```{r}
moviesAreTheBest %>%
  filter(distributor == "Walt Disney") %>%
  ggplot(aes(x=genre,y=production_budget, fill = genre)) + # add COLOR
  geom_boxplot(show.legend = FALSE)
```

```{r}
moviesAreTheBest %>%
  filter(distributor=="Walt Disney") %>%
  mutate(year = year(release_date)) %>%
  group_by(year) %>%
  summarize(avg_budget = mean(production_budget)) %>%
  ggplot(aes(x=year, y=avg_budget)) +
  geom_line()
```

```{r}
line_graph <- moviesAreTheBest %>%
  filter(distributor=="Walt Disney") %>%
  mutate(year = year(release_date)) %>%
  group_by(year) %>%
  summarize(avg_budget = mean(production_budget)) %>%
  ggplot(aes(x=year, y=avg_budget)) +
  geom_line()

ggplotly(line_graph)
```



